steps:
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['ci']

  - name: 'node:22'
    entrypoint: 'npm'
    args: ['run', 'test:ci']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/omni-deploy-run/myapps/my-sample-notes:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/omni-deploy-run/myapps/my-sample-notes:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'IMAGE=us-central1-docker.pkg.dev/omni-deploy-run/myapps/my-sample-notes:$SHORT_SHA'
    script: |
      gcloud run deploy my-simple-notes-us \
        --image "$IMAGE" \
        --region us-central1 \
        --platform managed \
        --allow-unauthenticated \
        --port 80

images:
  - 'us-central1-docker.pkg.dev/omni-deploy-run/myapps/my-sample-notes:$SHORT_SHA'

timeout: '1200s'

options:
  substitution_option: 'ALLOW_LOOSE'
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
