apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-sample-notes-app-prod
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
    spec:
      serviceAccountName: demo-svc@omni-deploy-run.iam.gserviceaccount.com
      containers:
        - name: my-sample-notes
          image: my-sample-notes
