apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-sample-notes-app-test
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      serviceAccountName: demo-svc@${PROJECT_ID}.iam.gserviceaccount.com
      containers:
        - name: my-sample-notes
          image: my-sample-notes
skaffold build --interactive=false --default-repo $env:REGION-docker.pkg.dev/omni-deploy-run/myapps --file-output artifacts.json