apiVersion: skaffold/v3
kind: Config
metadata:
  name: my-sample-notes
build:
  artifacts:
    - image: my-sample-notes
      context: ../
  googleCloudBuild:
    projectId: omni-deploy-run
    serviceAccount: projects/omni-deploy-run/serviceAccounts/cloud-build-custom-sa@omni-deploy-run.iam.gserviceaccount.com
deploy:
  cloudrun: {}
profiles:
  - name: test
    manifests:
      rawYaml:
        - notes-app-test.yaml
  - name: staging
    manifests:
      rawYaml:
        - notes-app-staging.yaml
  - name: prod
    manifests:
      rawYaml:
        - notes-app-prod.yaml
